version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  demo:
    image: demo-app:latest
    build:
      context : .
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

